#The Following is a sample configuration for an IPSEC IKEV2 Configuration for a Mikrotik RouterOS 6.48.1

#Define the ISAKMP Encryption Algorithms and Name a Proposal
/ip ipsec proposal
add auth-algorithms=sha256 enc-algorithms=aes-256-cbc,aes-256-ctr,aes-256-gcm name=Perimeter81-Proposal pfs-group=modp2048

#Define the IPSEC Encryption Algorithms and Name a Profile
/ip ipsec profile
add dh-group=modp2048 dpd-interval=10s enc-algorithm=aes-256 hash-algorithm=sha256 name=Perimeter81

#Define the Peer and ISKAKMP Mode
/ip ipsec peer
add address=131.226.32.161 exchange-mode=ikev2 local-address=35.172.43.104 name=Perimeter81 profile=Perimeter81

#Defind the Identity and Pre Share Key
/ip ipsec identity
add my-id=address:35.172.43.104 peer=Perimeter81 secret=passw0rd1

#Create the Interesting Traffic Profile
/ip ipsec policy
add dst-address=0.0.0.0/0 peer=Perimeter81 proposal=Perimeter81-Proposal sa-dst-address=131.226.32.161 sa-src-address=35.172.43.104 src-address=0.0.0.0/0 tunnel=yes

#Ensure the Firewall Permits the Access
/ip firewall address-list


# Create Address Lists to Use in Policy
/ip firewall address-list
add address=131.226.32.161 list=IPSECPEER
add address=0.0.0.0/0 list=VPN
add address=0.0.0.0/0 list=VPN

#Create Firewall access for IPSEC
/ip firewall filter
add action=accept chain=input dst-port=500,4500 protocol=udp src-address-list=IPSECPEER

# Allow Access between the Subnets
/ip firewall filter
add action=accept chain=forward src-address-list=VPN

#Perform Identity NAT on the Traffic between the networks
/ip firewall nat
add action=accept chain=srcnat dst-address-list=VPN src-address-list=VPN

### Add Loopback Interface for Peering
/interface bridge
add name=lo0

## BGP Config
/routing bgp instance
set default as=64550 client-to-client-reflection=yes !cluster-id !confederation disabled=no ignore-as-path-len=no name=default \
    out-filter="" redistribute-connected=yes redistribute-ospf=no redistribute-other-bgp=no redistribute-rip=no redistribute-static=\
    no router-id=169.254.100.2 routing-table=""
/routing bgp network
add disabled=no network=0.0.0.0/0 synchronize=yes
/routing bgp peer
add address-families=ip !allow-as-in as-override=no default-originate=never disabled=no hold-time=3m in-filter="" instance=default \
    !keepalive-time !max-prefix-limit !max-prefix-restart-time multihop=no name=VPN nexthop-choice=default out-filter="" passive=no \
    remote-address=169.254.100.1 remote-as=64512 remove-private-as=no route-reflect=no tcp-md5-key="" ttl=255 update-source=lo0 \
    use-bfd=no
add name=VPN remote-address=169.254.100.1 update-source=lo0