name: Python Security
on: [push]

jobs:
  security_checks:
    runs-on: self-hosted
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v3
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
